### ISSUE TITLE
 File Info,  field on_cloud is False even though it has been committed

### ISSUE THREAD

**Issue by haule24hdev** [0chain/blobber#107] opened 2021-05-04 03:27 UTC
![Screenshot from 2021-05-04 10-14-54](https://user-images.githubusercontent.com/50743635/116957945-533c6800-acc3-11eb-8a71-1c82ab1cd237.png)
![Screenshot from 2021-05-04 10-14-11](https://user-images.githubusercontent.com/50743635/116957953-57688580-acc3-11eb-9a90-df938c59b3da.png)
![Screenshot from 2021-05-04 10-13-58](https://user-images.githubusercontent.com/50743635/116957960-5b94a300-acc3-11eb-9d73-7b7342ce7f26.png)

**Comment by haule24hdev** [comment] 2021-05-04 03:31
@andrenerd check help me. I can't assign for you from require of @guruhubb

**Comment by andrenerd** [comment] 2021-05-12 02:47
@haule24hdev 
It's needed to reproduce the issue and to collect logged output. Please, repeat all the necessary steps for new file and share the logger output here. Probably it could be done with `zbox` command line tool. It lets to display logger output with "--verbose" flag.

The output should contain at least one of the "strings":
```
Logger.Error("Unable to fetch allocation with error", zap.Any("allocationID", fileRef.AllocationID), zap.Error(err))

Logger.Error("Error uploading cold data to cloud", zap.Error(err), zap.Any("file_name", fileRef.Name), zap.Any("file_path", fileObjectPath))

Logger.Error("Failed to update reference_object for on cloud true", zap.Error(err))

Logger.Info("Successfully uploaded file to cloud", zap.Any("file_name", fileRef.Name), zap.Any("allocation", fileRef.AllocationID))
```

Please, share the output here.
If there is no one of the listed strings present, please, copy-past the whole output.

**Comment by guruhubb** [comment] 2021-06-05 22:44
@andrenerd you can do this locally and with explorer code - may be faster than asking Hau.

**Comment by guruhubb** [comment] 2022-04-23 00:04
@cnlangzi is this related to the write marker issue, which may block @Shrhawk. Also we need the change the name on_cloud to on_chain as its related to Blockchain Awareness

**Comment by lpoli** [comment] 2022-04-23 03:18
@guruhubb This is actually a field that points whether the file is in disk or on cloud(minio). This is not related to writemarker registered in blockchain.

Its only used by blobber to serve some file. If its on cloud then it will fetch from cloud and serve to the request

So I think this issue can be closed.

**Comment by cnlangzi** [comment] 2022-04-23 07:47
it can't be closed. because `on_chain` is a new field asked from front-end team. They used `on_cloud` in past code. it is mistake.

**Comment by moldis** [comment] 2022-04-25 09:54
Closed

**Comment by cnlangzi** [comment] 2022-04-25 09:57
> Closed

it is not fixed yet

**Comment by Shrhawk** [comment] 2022-04-25 10:08
@cnlangzi why its closed ?

**Comment by moldis** [comment] 2022-04-25 10:41
Agh, sorry accidentally closed it

**Comment by cnlangzi** [comment] 2022-04-25 11:59
@Shrhawk a new field `on_chain` should be added on blobber side. and check its related WM before updating it with true. NB. don't make any change on `on_cloud`. it is designed for minio.

**Comment by guruhubb** [comment] 2022-05-04 18:03
@avanaur can take this issue to complete the write marker flow

**Closed** 2022-05-06 00:25 UTC
Labels: bug, good first issue, mainnet
